apiVersion: kustomize.config.k8s.io/v1beta1
kind:       Kustomization
resources:
  - all.yaml
patchesStrategicMerge:
  - replace_crds.yaml
generatorOptions:
  labels:
    grafana_dashboard: "1"
configMapGenerator:
  - name: longhorn-dashboard-cm
    files:
      - dashboards/longhorn-dashboard.json
  - name: argocd-dashboard-cm
    files:
      - dashboards/argocd-dashboard.json
