kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: null
    admin:
      existingSecret: grafana-admin
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      hosts:
        - grafana.malteesch.io
      tls:
        - secretName: grafana-malteesch-io-tls
          hosts:
            - grafana.malteesch.io
    grafana.ini:
      server:
        root_url: https://grafana.malteesch.io
  prometheus:
    prometheusSpec:
      retentionSize: 29GB
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn-nvme
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 30Gi
